secret = "425198068673003502071727491385930554321152168964846181849824171598229615114"
blinder = "323272948098037011726179213312742359831664984995464090221477125674202708984"
zk_commitment = "0x1a55896b81b560c9e35da7cd69a6a56f5a6cf1d75866550d677ff8fe1df8dacb"
nullifier_hash = "0x1368bcd53e1a8f43f822bd945539cb47ad3a3448fa2e0c54660881f0da266ee9"
denomination = "0"
recipient = "0x1234abcd"
